CREATE TABLE T_P_AO_VAT_PLAN_DETA_bak AS SELECT * FROM T_P_AO_VAT_PLAN_DETA;
DELETE FROM T_P_AO_VAT_PLAN_DETA;
alter table T_P_AO_VAT_PLAN_DETA modify C_INTERBANK_TRADE VARCHAR2(10);
INSERT INTO T_P_AO_VAT_PLAN_DETA VALUE SELECT * FROM T_P_AO_VAT_PLAN_DETA_bak;
DROP TABLE T_P_AO_VAT_PLAN_DETA_bak;
COMMIT;